### ISSUE TITLE
Finer grained control over date/time parsing

### ISSUE THREAD

**Issue by chris-prener** [shaughnessyar/driftR#37]
Right now we don't provide a window into date/time parsing in terms of the `order` used by `lubridate` - we could add this into the APIs for `dr_factor`, `dr_replace`, and `dr_drop`.

**Comment by chris-prener** [comment]
I... am really not sure what this is about. @shaughnessyar - do you have an idea?

**Comment by shaughnessyar** [comment]
@chris-prener Yes, I think you wanted to add an argument to let the user select the "orders" in the `parse_date_time` for `dr_factor`. I think, however, that this probably is not necessary. We include all the common date-time formats as default. I have never seen a dataset that produces say year-day-month or month-year-day formats. I think we should balance functionality with ease of use. Adding another argument might make the function too complex because the user will need to understand how to express the format of their date-time variable.

**Comment by chris-prener** [comment]
ok sounds good - let's close this!
